# Application-level configuration
application:
  # Name specifies the name of the application
  name: "Application Service"
  # Version specifies the version of the application
  version: "1.0.0"

# Server configuration
server:
  # Port specifies the port number the server will listen on
  port: 8080
  # ReadTimeout defines the maximum duration for reading the entire request, including the body, in seconds
  read_timeout: 15
  # WriteTimeout defines the maximum duration before timing out writes of the response, in seconds
  write_timeout: 15
  # ShutdownTimeout defines the maximum duration the server will wait for active connections to finish during shutdown, in seconds
  shutdown_timeout: 30

# Database configuration
database:
  # PostgreSQL-specific settings
  postgres:
    # Host specifies the database server host
    host: "localhost"
    # Port specifies the database server port
    port: 5432
    # User specifies the database user
    user: "user"
    # Password specifies the database password
    password: "secret"
    # DBName specifies the database name
    dbname: "test"
    # Schema specifies the database schema
    schema: "public"
    # SSLMode specifies the SSL mode for database connection
    sslmode: "disable"
    # MaxIdleConns specifies the maximum number of idle connections in the pool
    max_idle_conns: 10
    # MaxOpenConns specifies the maximum number of open connections to the database
    max_open_conns: 100
    # ConnMaxIdleTime specifies the maximum amount of time a connection may be idle, in minutes
    conn_max_idle_time: 5
    # ConnMaxLifetime specifies the maximum amount of time a connection may be reused, in minutes
    conn_max_lifetime: 60
    # Debug enables or disables debug mode for database operations
    debug: true
    # IsUseMigrate specifies whether to use database migration
    is_use_migrate: true

  # Redis configuration for caching and stateful JWT management
  redis:
    # Addrs specifies the Redis server addresses (array of host:port)
    addrs:
      - "localhost:6379"
    # Username specifies the Redis username (leave empty if not required)
    username: ""
    # Password specifies the Redis password (leave empty if not required)
    password: ""
    # DB specifies the Redis database number (0-15)
    db: 0
    # PoolSize specifies the maximum number of socket connections
    pool_size: 10

# Security configuration for authentication and authorization
security:
  # JWT token configuration
  jwt:
    # AccessTokenSecret is the secret key for signing access tokens (use a strong, random string in production)
    access_token_secret: "your-access-token-secret-key-here"
    # RefreshTokenSecret is the secret key for signing refresh tokens (use a different strong, random string in production)
    refresh_token_secret: "your-refresh-token-secret-key-here"
    # AccessTokenExpiry is the expiry time for access tokens in minutes
    access_token_expiry: 15
    # RefreshTokenExpiry is the expiry time for refresh tokens in hours
    refresh_token_expiry: 168  # 7 days
    # Stateful indicates whether to use stateful token management with Redis (true) or stateless (false)
    stateful: true