# Application-level configuration
application:
  # Name specifies the name of the application
  name: "Supplier Credentials Service"
  # Version specifies the version of the application
  version: "1.0.0"

# Server configuration
server:
  # Port specifies the port number the server will listen on
  port: 8081
  # ReadTimeout defines the maximum duration for reading the entire request, including the body, in seconds
  read_timeout: 15
  # WriteTimeout defines the maximum duration before timing out writes of the response, in seconds
  write_timeout: 15
  # ShutdownTimeout defines the maximum duration the server will wait for active connections to finish during shutdown, in seconds
  shutdown_timeout: 30

# Infrastructure configuration
infrastructure:
  # PostgreSQL-specific settings
  postgres:
    # Host specifies the database server host
    host: "localhost"
    # Port specifies the database server port
    port: 5432
    # User specifies the database user
    user: "beni"
    # Password specifies the database password
    password: "Password123"
    # DBName specifies the database name
    dbname: "b2b"
    # Schema specifies the database schema
    schema: "supplier_credentials_service"
    # SSLMode specifies the SSL mode for database connection
    sslmode: "disable"
    # MaxIdleConns specifies the maximum number of idle connections in the pool
    max_idle_conns: 10
    # MaxOpenConns specifies the maximum number of open connections to the database
    max_open_conns: 100
    # ConnMaxIdleTime specifies the maximum amount of time a connection may be idle, in minutes
    conn_max_idle_time: 5
    # ConnMaxLifetime specifies the maximum amount of time a connection may be reused, in minutes
    conn_max_lifetime: 60
    # Debug enables or disables debug mode for database operations
    debug: true
    # IsUseMigrate specifies whether to use database migration
    is_use_migrate: true

# Security configuration for authentication and authorization
security:
  # Encryption configuration
  encryption:
    # Key is the encryption key for credentials (must be 32 bytes for AES-256)
    key: "your-32-byte-encryption-key-here"